language: csharp  	
sudo: required  	
dist: trusty	
env:  	
  - CLI_VERSION=latest	
mono:  	
  - 5.10.0	
dotnet: 2.1.400	
os:	
  - linux	
branches:  	
  only:	
    - master	
    - /.*/	
before_script:	
- chmod +x ./build.sh	
- curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg	
- sudo mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg	
- sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-trusty-prod trusty main" > /etc/apt/sources.list.d/dotnetdev.list'	
- sudo apt-get update	
- sudo apt-get install dotnet-dev-1.1.9	
before_install:	
  - sudo apt install nuget	
script:  	
  - ./build.sh